name: Echo Temperature from Airflow

# Enables manual triggering of the workflow with inputs
on:
  workflow_dispatch:
    inputs:
      temperature:
        description: 'Temperature data from Airflow'
        required: true
        default: '25' # Default temperature

jobs:
  echo_temperature:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the temperature
        run: echo "The temperature passed from Airflow is ${{ github.event.inputs.temperature }}°C"
